POST http://localhost:3003/api/blogs
Content-type: application/json

{
    "title": "Koti kuntoon rahalla",
    "author": "Aulis Apunen",
    "url": "http://www.mtv.fi",
    "likes": 0,
    "user": "5d99f29e4f1cd43fa0ea87d9"
}

###

POST http://localhost:3003/api/blogs
Content-type: application/json

{
    "title": "Minä, Aku Ankka",
    "author": "Carl Barks",
    "url": "http://www.efora.fi",
    "likes": 0,
    "user": "5d99f29e4f1cd43fa0ea87d9"
}


###

POST http://localhost:3003/api/blogs
Content-type: application/json

{
    "title": "Taisteluni (ja mitä tekisin toisin)",
    "author": "Ilkka Kanerva",
    "url": "http://www.Kempele.fi",
    "likes": 0,
    "user": "5d99f2f34f1cd43fa0ea87dc"
}

###

POST http://localhost:3003/api/blogs
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlcHBvIiwiaWQiOiI1ZDlhMTJlMWU0MmRjZDQ0MjQ5OGQ1NDAiLCJpYXQiOjE1NzYwMDIwMDZ9.yboQ5nB5DCU-3Utc9wDPEGW5Lk13gzNenFpyZ3rER1M

{
    "title": "Radio ja petankki",
    "author": "Francois Marconi",
    "url": "http://www.wsoy.fi",
    "likes": 0,
    "user": "5d99f2f34f1cd43fa0ea87dc"
}


###

POST http://localhost:3003/api/blogs/5d9a1398d908e332d848087d/comments
Content-type: application/json

{
    "commentText": "Hyvästi sanottu."
}


