POST http://localhost:3003/api/blogs
Content-type: application/json

{
    "title": "Koti kuntoon rahalla",
    "author": "Aulis Apunen",
    "url": "http://www.mtv.fi",
    "likes": 0
}

###

POST http://localhost:3003/api/blogs
Content-type: application/json

{
    "title": "Minä, Aku Ankka",
    "author": "Carl Barks",
    "url": "http://www.efora.fi",
    "likes": 0
}


###

POST http://localhost:3003/api/blogs
Content-type: application/json

{
    "title": "Taisteluni (ja mitä tekisin toisin)",
    "author": "Ilkka Kanerva",
    "url": "http://www.Kempele.fi",
    "likes": 0
}
